#./low_dram_bw_build_champsim.sh hashed_perceptron no no no no no no no lru lru lru srrip drrip lru lru lru 1 
#./low_dram_bw_build_champsim.sh hashed_perceptron no ipcp_isca2020 no no no no no lru lru lru srrip drrip lru lru lru 1
#./low_dram_bw_build_champsim.sh hashed_perceptron no ipcp_isca2020 ipcp_isca2020 no no no no lru lru lru srrip drrip lru lru lru 1
#./low_dram_bw_build_champsim.sh hashed_perceptron no no bingo_dpc3 no no no no lru lru lru srrip drrip lru lru lru 1 
#./low_dram_bw_build_champsim.sh hashed_perceptron no no spp no no no no lru lru lru srrip drrip lru lru lru 1
#./low_dram_bw_build_champsim.sh hashed_perceptron no no ppf no no no no lru lru lru srrip drrip lru lru lru 1 
#./low_dram_bw_build_champsim.sh hashed_perceptron no ipcp_isca2020_critical no no no no no lru lru lru srrip drrip lru lru lru 1
#./low_dram_bw_build_champsim.sh hashed_perceptron no ipcp_isca2020_critical ipcp_isca2020_critical no no no no lru lru lru srrip drrip lru lru lru 1 
./low_dram_bw_build_champsim.sh hashed_perceptron no no bingo_critical no no no no lru lru lru srrip drrip lru lru lru 1
#./low_dram_bw_build_champsim.sh hashed_perceptron no no spp_critical no no no no lru lru lru srrip drrip lru lru lru 1
#./low_dram_bw_build_champsim.sh hashed_perceptron no no ppf_critical no no no no lru lru lru srrip drrip lru lru lru 1
#./low_dram_bw_build_champsim.sh hashed_perceptron fnlmma_25KB no no no no no no lru lru lru srrip drrip lru lru lru 1
#./low_dram_bw_build_champsim.sh hashed_perceptron fnlmma_25KB ipcp_isca2020 no no no no no lru lru lru srrip drrip lru lru lru 1
#./low_dram_bw_build_champsim.sh hashed_perceptron fnlmma_25KB ipcp_isca2020 ipcp_isca2020 no no no no lru lru lru srrip drrip lru lru lru 1 
#./low_dram_bw_build_champsim.sh hashed_perceptron fnlmma_25KB no bingo_dpc3 no no no no lru lru lru srrip drrip lru lru lru 1
#./low_dram_bw_build_champsim.sh hashed_perceptron fnlmma_25KB no spp no no no no lru lru lru srrip drrip lru lru lru 1
#./low_dram_bw_build_champsim.sh hashed_perceptron fnlmma_25KB no ppf no no no no lru lru lru srrip drrip lru lru lru 1
#./low_dram_bw_build_champsim.sh hashed_perceptron fnlmma_25KB ipcp_isca2020_critical no no no no no lru lru lru srrip drrip lru lru lru 1
#./low_dram_bw_build_champsim.sh hashed_perceptron fnlmma_25KB ipcp_isca2020_critical ipcp_isca2020_critical no no no no lru lru lru srrip drrip lru lru lru 1
./low_dram_bw_build_champsim.sh hashed_perceptron fnlmma_25KB no bingo_critical no no no no lru lru lru srrip drrip lru lru lru 1
#./low_dram_bw_build_champsim.sh hashed_perceptron fnlmma_25KB no spp_critical no no no no lru lru lru srrip drrip lru lru lru 1
#./low_dram_bw_build_champsim.sh hashed_perceptron fnlmma_25KB no ppf_critical no no no no lru lru lru srrip drrip lru lru lru 1
