./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver client_001.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver client_002.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver client_003.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver client_004.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver client_005.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver client_006.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver client_007.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver client_008.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_001.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_003.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_004.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_009.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_010.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_011.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_012.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_013.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_014.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_016.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_017.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_018.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_019.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_020.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_021.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_022.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_023.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_024.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_025.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_026.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_027.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_028.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_029.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_030.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_031.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_032.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_033.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_034.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_035.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_037.champsimtrace.xz stats/spp/cs/DIV4 &
./run_champsim.sh bimodal-no-no_DRAMIOFREQDIV4-spp-no-no-no-no-lru-lru-lru-lru-lru-lru-lru-lru-1core 10 50 traces/clientserver server_038.champsimtrace.xz stats/spp/cs/DIV4 &
